### ISSUE TITLE
CNAME only in response

### ISSUE THREAD

**Issue by treussart** [domainr/dnsr#123]
If a server is doing a recursion, asks for a record type that is not CNAME, but gets a CNAME response, then it should restart the query with the name from the CNAME record, merge the response from the restarted query with the CNAME response and return the combined response to whoever it was doing the recursion for.

example: 
```
➜  ~ dig @127.0.0.1 -p 5000 +tcp translate.google.com A

; <<>> DiG 9.18.25 <<>> @127.0.0.1 -p 5000 +tcp translate.google.com A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41052
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;translate.google.com.		IN	A

;; ANSWER SECTION:
translate.google.com.	300	IN	CNAME	www3.l.google.com.
```
I want in the response also the IP for A type:
```
www3.l.google.com.	300	IN	A	172.217.18.206
```

**Comment by cee-dub** [comment]
Thanks for the report! I've fixed it in #124
