### ISSUE TITLE
explore parallelism and racing

### ISSUE THREAD

**Issue by case** [domainr/dnsr#13]
Per our discussion yesterday:

- recently we've noticed some DNS timeouts in production, which we suspect could be something like DNSR querying a nameserver that's been taken out of rotation
- the idea here is to explore checking all the available nameservers in parallel, then bail once there's an answer from any of them
- goal is to address the "context deadline exceeded" errors we're seeing in production

**Comment by ydnar** [comment]
`MaxNameservers` == 2 in https://github.com/domainr/dnsr/blob/master/resolver.go#L17

- We could increase `MaxNameservers` to 3 or 4.
- We could randomly iterate more name servers.

**Comment by case** [comment]
This was addressed in #14.
