### ISSUE TITLE
Set request deadline at 5s

### ISSUE THREAD

**Issue by cee-dub** [domainr/dnsr#3]
We currently set 5s timeouts for each stage of a DNS request (connect, write, read) at 5s, which results in an unpredictable upper bound on latency. We would like to set an absolute upper boundfor latency at 5s, which should be straightforward to achieve with a network deadline on the client.

**Comment by cee-dub** [comment]
If this is tuned too tightly, we could flap or stay down when things are flaky but not entirely out (_e.g._ recent UltraDNS outage). Suggested tuning is solely based on intuition, not actual measurements. We could implement this in two parts where we measure the latency for a week or two and then set the unhealthy threshold above the noise floor.

**Comment by wbond** [comment]
From reading through the code, it seems github.com/miekg/dns is adding the timeout to the current time to set individual deadlines for dial, read, write. Instead we'll calculate our own final deadline before dialing and just reach into `dns.Client.Conn` to set it for read/write.

**Comment by wbond** [comment]
It was decided that this is not the approach we want to take for timeouts.
