### ISSUE TITLE
Add TTL support?

### ISSUE THREAD

**Issue by bookmoons** [domainr/dnsr#31]
I'm evaluating this for possible use in another project. It seems to be the nicest resolver available, but I need something with an expiring cache that respects TTL.

Would the team consider a PR to support TTL?

**Comment by bookmoons** [comment]
@ydnar @case Sorry for the ping guys. Wasn't sure if the issue will be seen. I'm inclined to write a patch for this but wanted to ask first if getting it in is a possibility.

**Comment by cee-dub** [comment]
Thanks for proposing this. Would you tell us a bit about the design you have in mind to add the feature?

**Comment by bookmoons** [comment]
Thanks for looking at it. I've looked over it a little. The underlying `miekg/dns` exposes TTL. There's a cache built around this [RR struct](https://github.com/domainr/dnsr/blob/master/rr.go). It's a benefit this is already structured data, I was looking at other caches but they all store string values.

TTL can be stored in this record when retrieved. Cache reads can then verify liveness and only return if the entry is live. That happens [here](https://github.com/domainr/dnsr/blob/7699a8b628e079f59bf69d4ef1ec65600844eeac/resolver.go#L92) so an expired entry would trigger a standard query to DNS again.

I'd make it optional so when it's disabled you're not storing TTLs unnecessarily.

**Comment by cee-dub** [comment]
Will definitely look at a PR. If you can share your use case, that will help us with context, too. Thanks!

**Comment by bookmoons** [comment]
Wonderful.

**Comment by bookmoons** [comment]
Made a submission #32 to start this off.
