### ISSUE TITLE
Multitype query?

### ISSUE THREAD

**Issue by bookmoons** [domainr/dnsr#35]
I'm hitting an issue due to the IP version split. Trying to query for both versions can lead to a network exchange on every resolution.

What would you guys think about supporting multitype queries? Behavior would be: First check cache for all the types. Only hit the network if we have none of them. Short circuit at the soonest point so you do the minimum network exchange. This is currently not possible externally, since cache is inaccessible.

Motivation is the common situation where a server only has an IPv4 address. You'd like to query for v6 but if you get v4 stick with it. So you don't keep hitting the network on every resolution.

```go
rrs := resolver.ResolveAlternate("example.com", []string{"AAAA", "A"})
```

[`bookmoons/resolve-alternate`](https://github.com/domainr/dnsr/compare/master...bookmoons:bookmoons/resolve-alternate) has a working implementation.

Analagous logic with the current version that hits network every time:

```DNS Zone
example.com.  IN  A     192.0.2.1
```

```go
func resolveIP() {
    ipv6s := resolver.Resolve("example.com", "AAAA")
    if len(ipv6s) > 0 {
        return ipv6s
    }
    ipv4s := resolver.Resolve("example.com", "A")
    if len(ipv4s) > 0 {
        // Cache for type A only hit after network query for AAAA
        return ipv4s
    }
    return emptyRRs
}
```

**Comment by bookmoons** [comment]
@cee-dub @ydnar Sorry to chase guys, wasn't sure if this had been seen. Is this something you guys would consider?

**Comment by cee-dub** [comment]
Sounds similar to [Happy Eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs).

Why not check the cache for all requested types before a query, instead of returning early in https://github.com/domainr/dnsr/compare/master...bookmoons:bookmoons/resolve-alternate#diff-6756fdfda338c13b910a6416f2ac9f54R166 ?

**Comment by bookmoons** [comment]
That's an interesting protocol.

If that logic is better I can update. I'm only using 1 address so as soon as it has anything it's enough. Started calling it `ResolveAny` but I didn't want to collide with the `ANY` query type.
