### ISSUE TITLE
Ability to specify source address of requests [Feature Request]

### ISSUE THREAD

**Issue by moredure** [domainr/dnsr#40]
Use case is a web server with many public IP addresses and you need to specify exactly one specific to access the internet.

**Comment by ydnar** [comment]
Can you describe your use case and proposed API?

**Comment by moredure** [comment]
server with multiple-public ips, maybe load balancing across them

**Comment by ydnar** [comment]
That may be a request for https://github.com/miekg/dns, the library this package uses internally for making DNS network requests.
